### ISSUE TITLE
Upload clean, refined and collected data

### ISSUE THREAD

**Issue by shionguha** [marquettecomputationalsocialscience/summer2018reu#2]
1. Upload clean, refined and collected data.'

2. Upload data description document so that Teams 1 and 2 can read through and understand the data.

**Comment by chrissupinger** [comment]
# Datasets

Location: https://github.com/marquettecomputationalsocialscience/mkecrimeoutcomedata/tree/master/datasets

Data Description:  [Data Description.pdf](https://github.com/marquettecomputationalsocialscience/summer2018reu/files/2066642/Data.Description.pdf)


## Municipal Court Schemas

- Business violations, 2012 - 2016
- Missing cases, 2012 - 2016
- General persons charged, 2012 - 2016
- Parking violations, 2012 - 2016
- Warrants, 2012 - 2016

## Working / Pending

- Final cases for year 2011 still being sanitized; upload expected 4 - 5 June
- Cases for year 2017 will follow upload of 2011 cases; will being work with year 2018 afterwards
- Refining regular expression program for GIS API integration
- Continued work with Circuit Court schemas

**Comment by shionguha** [comment]
Thanks! Great work!
