### ISSUE TITLE
Week 2 (June 5 - 11): Investigating Clustering Methods

### ISSUE THREAD

**Issue by shionguha** [marquettecomputationalsocialscience/summer2018reu#3]
1. Investigate prevalent clustering families and create a report (due via pull request on June 11). This report should have description of the most popular algorithm from each family as well as a description of potential points of inflection where bias may occur. Visualizations are greatly recommended.

2. Present said report collaboratively on June 12 lab meeting.

**Comment by shionguha** [comment]
@supcl : Could you please check the deliverables from the students and close this issue?

**Comment by 6119greend** [comment]
[User Election in Clustering Algorithms powerpoint#### presentation draft.pptx](https://github.com/marquettecomputationalsocialscience/summer2018reu/files/2100059/User.Election.in.Clustering.Algorithms.powerpoint.presentation.draft.pptx)


[cluster_exploration.ipynb.txt](https://github.com/marquettecomputationalsocialscience/summer2018reu/files/2100061/cluster_exploration.ipynb.txt)
