### ISSUE TITLE
Week (June 5 - 11): Investigating Kernel Density Estimates

### ISSUE THREAD

**Issue by shionguha** [marquettecomputationalsocialscience/summer2018reu#4]
1. Investigate KDE's for points of inflection and create a report (due via pull requests on June 11). This report should describe what KDEs do and points where bias may occur. Visualizations are greatly recommended.

2. Present report in June 12 lab meeting.

**Comment by chrissupinger** [comment]
[KDE Prelim.pdf](https://github.com/marquettecomputationalsocialscience/summer2018reu/files/2096240/KDE.Prelim.pdf)
